libs =
import libs += toml11%lib{toml11}
import libs += libboost-test%lib{boost_test}

tests/
{
    for test_cxx_file : cxx{* -{test_windows test_multiple_translation_unit_*}}
    {
        test_name = $name($test_cxx_file) # Get the pure cxxfile name.

        ./: exe{$test_name}: cxx{$test_name} hxx{**} $libs

        # The cxx starting with 'check' is a utility checker, not a unit test, using different testscript.
        exe{$test_name}: testscript{../test_check_utils}: include = ($test_name == 'check' || $test_name == 'check_serialization')
        
        toml_files_for_test = file{**.toml}
        exe{$test_name}: testscript{../test_common} $toml_files_for_test: include = ($test_name != 'check' && $test_name != 'check_serialization')
    }

    # Build test_multiple_translation_unit_*.cpp.
    ./: exe{test_multiple_translation_unit}: cxx{test_multiple_translation_unit_*} hxx{**} $libs

    # Build test_windows.cpp only on Windows.
    ./: exe{test_windows}: include = ($cxx.target.class == 'windows') # Should not write if windows here, see https://github.com/build2/HOWTO/blob/master/entries/keep-build-graph-config-independent.md
    exe{test_windows}: cxx{test_windows} hxx{**} $libs
}

# cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.poptions =+ "-DUNITTEST_FRAMEWORK_LIBRARY_EXIST" # Fixed BOOST_TEST_NO_LIB redefined warning.

# Ignore some warning in test on gcc
if ($cxx.class == 'gcc')
{
    cxx.coptions += "-Wno-dangling-reference" "-Wno-sign-compare" "-Wno-unused" "-Wno-deprecated"
}