libs =
import libs += toml11%lib{toml11}
import libs += libboost-test%lib{boost_test}

# exe{toml11-tests}: {hxx ixx txx cxx}{**} $libs

tests/
{
    for test_cxx_file : cxx{* -{test_windows test_comments test_serialize_file test_multiple_translation_unit_*}}
    {
        test_name = $name($test_cxx_file) # Get the pure cxxfile name.
        
        ./: exe{$test_name}: cxx{$test_name} hxx{**} $libs

        if ($test_name == 'check' || $test_name == 'check_serialization')
        {
            info $test_name
            exe{$test_name}: testscript{../test_check}
        }
        else
        {
            exe{$test_name}: testscript{../test_common}
        }
    }
}

# cxx.poptions =+ "-I$out_root" "-I$src_root"
